<?php

/*
 * Color
 */
define('GOLD', -1);
define('PEARL', 0);
define('BLUE', 1);
define('WHITE', 2);
define('GREEN', 3);
define('BLACK', 4);
define('RED', 5);
define('GLASSWARE', 6);

define('GRAY', 9);
define('MULTICOLOR', 9);

/*
 * Powers
 */
define('POWER_PLAY_AGAIN', 1);
define('POWER_MULTICOLOR', 2);
define('POWER_TAKE_GEM_FROM_TABLE', 3);
define('POWER_TAKE_PRIVILEGE', 4);
define('POWER_TAKE_GEM_FROM_OPPONENT', 5);
const POWER_RESERVE_CARD = 6;
const POWER_WIN_9PTS_SAME_COLOR = 7;
const POWER_WIN_9CROWNS = 8;
const POWER_TAKE_ALL_GEMS_SAME_COLOR = 9;
const POWER_TAKE_COUNTERFEITER_CARD = 10;
const POWER_TAKE_2GEMS_FROM_BAG = 11;
const POWER_TAKE_GOLD_FROM_TABLE = 12;
const POWER_TAKE_3GEMS_FROM_TABLE = 13;

/*
 * State constants
 */
define('ST_BGA_GAME_SETUP', 1);

define('ST_PLAYER_USE_PRIVILEGE', 10);

define('ST_PLAYER_PLAY_ACTION', 30);

define('ST_PLAYER_RESERVE_CARD', 35);

define('ST_PLAYER_PLACE_JOKER', 40);

define('ST_PLAYER_TAKE_ROYAL_CARD', 50);
const ST_PLAYER_TAKE_COUNTERFEITER_CARD = 51;

define('ST_PLAYER_TAKE_BOARD_TOKEN', 55);

define('ST_PLAYER_TAKE_OPPONENT_TOKEN', 60);

const ST_PLAYER_BEFORE_END_TURN = 70;

const ST_PLAYER_RESERVE_FROM_DECK_CHOOSE_DECK = 71;
const ST_PLAYER_RESERVE_FROM_DECK_CHOOSE_CARD = 72;

define('ST_PLAYER_DISCARD_TOKENS', 80);

define('ST_NEXT_PLAYER', 85);

define('ST_END_SCORE', 90);

define('ST_END_GAME', 99);
define('END_SCORE', 100);

/*
 * Constants
 */
define('PLAY_AGAIN', 10);
define('PLAYED_CARD', 11);
define('TAKE_ROYAL_CARD', 12);
const PLAYER_REFILLED = 13;

/*
 * Options
 */

/*
 * Global variables
 */
const ROYAL_CARDS_WITH_COUNTERFEITER_POWER = 'ROYAL_CARDS_WITH_COUNTERFEITER_POWER';
const RESERVE_FROM_DECK = 'RESERVE_FROM_DECK';
const COUNTERFEITER13_USED = 'COUNTERFEITER13_USED';

?>
